### ISSUE TITLE
上传多张图片怎么弄

### ISSUE THREAD

**Issue by wlevene** [xiocode/weigo#10]

**Comment by xiocode** [comment]
不好意思啊，这个项目还是我四年前玩的，已经太久没有更新过了，我也不知道现在新浪的API是什么情况，我先去看看

**Comment by xiocode** [comment]
@GangWang 我看了下，需要高级接口权限
http://open.weibo.com/wiki/2/statuses/upload_url_text

**Comment by xiocode** [comment]
@GangWang https://github.com/wangdan/AisenWeiBo/blob/a1c583d2da056dec88992f3994b9706d4bb62921/app/src/main/java/org/aisen/weibo/sina/service/publisher/PublishManager.java#L339
可以参考一下这个，需要先将图片上传，然后获取多个ID，最后拼接到pic_ids然后发布。

**Comment by wlevene** [comment]
收到  感谢
